### ISSUE TITLE
BT testing

### ISSUE THREAD

**Issue by charlesbel** [ravnized/XiaoMi-Pro-enhanced-Hackintosh#1]
Hi,
First, thanks a lot for creating this repo, that was exactly what I searched.
I would like to share you a "working" Bluetooth Firmware : https://github.com/OpenIntelWireless/IntelBluetoothFirmware
I found it on ths page : https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Work-Around-with-Bluetooth
I think we can start with it in order to try to make the Bluetooth works. I already read that this Kext can cause some sleeping problems, but it seems to work.
I suggest you try it and if it works well, you can add it into the code of the repo.
Sincerely,
Charles

**Comment by charlesbel** [comment]
It seems that you already added it on your code, and itwln also. So why WIFI an BT won't work... ?

**Comment by ravnized** [comment]
At the moment the 9560v2 doesn't work cause it needs more testing, so if you want to help cause you're a programmer you can help going to this link [](https://github.com/OpenIntelWireless/IntelBluetoothFirmware), for the Bluetooth I didn't try to debug the problem yet.

**Comment by charlesbel** [comment]
> At the moment the 9560v2 doesn't work cause it needs more testing, so if you want to help cause you're a programmer you can help going to this link , for the Bluetooth I didn't try to debug the problem yet.

Wich link are you talking about ?

**Comment by ravnized** [comment]
The link for WiFi: [https://openintelwireless.github.io/itlwm/](url)

**Comment by charlesbel** [comment]
And you don't think we can try something like : https://youtu.be/kHfUjJ2RkyU

**Comment by ravnized** [comment]
I'm gonna try it and see if it works

**Comment by charlesbel** [comment]
> I'm gonna try it and see if it works

I think you should try this method with removing all kexts related to the Intel card, so itwln and Bluetooth Firmware also. I hope that will work. Let me know.

**Comment by ravnized** [comment]
Repo Updated, WIFI working

**Comment by charlesbel** [comment]
> Repo Updated, WIFI working

Great !!

**Comment by charlesbel** [comment]
Okay so now for the bluetooth, could you download the latest release of the IntelBluetooth : [https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases](https://github.com/OpenIntelWireless/IntelBluetoothFirmware/releases)
It was released 16 hours ago, and I think it should work !

**Comment by ravnized** [comment]
Nope, already updated, it doesn't work sadly

**Comment by charlesbel** [comment]
Hi, I just seen an update of itlwm, so now there is a new kext named AirportItlwm that allow you to use the native wifi instead of itlwm + Heliport, and maybe have a better wifi speed. I give you the link to the wiki to that you can put the new kext into your  EFI :
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Drive-Native-Intel-Wireless-Card
