### ISSUE TITLE
Update for Wifi

### ISSUE THREAD

**Issue by charlesbel** [ravnized/XiaoMi-Pro-Enhanced-Hackintosh#10]
Hi, I just seen an update of itlwm, so now there is a new kext named AirportItlwm that allow you to use the native wifi instead of itlwm + Heliport, and maybe have a better wifi speed. I give you the link to the wiki to that you can put the new kext into your EFI :
https://github.com/daliansky/XiaoMi-Pro-Hackintosh/wiki/Drive-Native-Intel-Wireless-Card

**Comment by mBilG** [comment]
I've tried it.. it works for me.. Not sure if anything else is affected though..
Thanks for the update

**Comment by sciro24** [comment]
Does the native wifi, without heliport improve performance? if it is possible to create a fixed EFI?

**Comment by mBilG** [comment]
Been working okay for me..
May need to reconnect after sleep.. but not a big deal for me.. 
performance is fine.. didn't test before and after..

**Comment by sciro24** [comment]
> Been working okay for me..
> May need to reconnect after sleep.. but not a big deal for me..
> performance is fine.. didn't test before and after..

can you send me your EFI with this mod?

**Comment by ildarnm** [comment]
I updated to the Big Sur and now WiFi doesn't show networks.

**Comment by ravnized** [comment]
The kext is AirportItlwm you can download the right version [Here](https://github.com/OpenIntelWireless/itlwm/releases)
