### ISSUE TITLE
0.6.3 Cannot use WiFi on Big Sur

### ISSUE THREAD

**Issue by TechEnco** [ravnized/XiaoMi-Pro-Enhanced-Hackintosh#13]
Catalina 10.15.6 upgraded to Big Sur 11.0.1，WiFi doesn't work，Heliport doesn't work either.

Copy Kexts and Config.plist from 0.6.1 to 0.6.3，You can use heliport on Big Sur.

The battery display is also delayed.

**Comment by TechEnco** [comment]
0.6.3，HeliPort on the left and Intel WiFi on the right, neither can be used.
![IMG_20201122_152838](https://user-images.githubusercontent.com/74847141/99897980-d2019380-2c95-11eb-96bd-922ccc6ffdae.png)

**Comment by TechEnco** [comment]
Replace Kexts and Config.plist, or use 0.6.1,
HeliPort can be used, but Intel WiFi cannot be used.
![IMG_20201122_154519](https://user-images.githubusercontent.com/74847141/99898260-fe1e1400-2c97-11eb-9402-c828810c48bb.png)

**Comment by ravnized** [comment]
If you're on  Big sur i reccomend using the last 1.2.0 alpha, and download the big sur version

**Comment by TechEnco** [comment]
It really works，thanks！
![截屏2020-11-22 下午10 56 47](https://user-images.githubusercontent.com/74847141/99907148-0e9fb000-2cd3-11eb-8dcc-6136f62a8c54.png)
