### ISSUE TITLE
Trackpad non working

### ISSUE THREAD

**Issue by sciro24** [ravnized/XiaoMi-Pro-Enhanced-Hackintosh#3]
Hi everyone, with this configuration the trackpad is not recognized and therefore the gestures do not work. I don't know if I did something wrong but it doesn't work for me.

**Comment by Tiku96** [comment]
Check on trackpad if is checked touch with 1 finger

**Comment by sciro24** [comment]
![Schermata 2020-09-14 alle 10 54 04](https://user-images.githubusercontent.com/66693795/93065249-c338a800-f678-11ea-9eca-f1a0968be46b.png)
the problem is that it is not recognized and does not work. how can I do ?

**Comment by Tiku96** [comment]
U have copy all folder EFI? check on ACPI if u have all file

**Comment by ravnized** [comment]
Try rebuilding the cache and see if it works
